// <auto-generated />
namespace HomeForPets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExpansionForm_SexColor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpansionForm_SexColor));
        
        string IMigrationMetadata.Id
        {
            get { return "202001201217373_ExpansionForm_SexColor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
